
#The configuration for this domain is used for all 'common' domains
JDns.master.zone=foo.com

#Below is a list of the other properties supported but all have reasonable default values.
#This point to a local file with properties external to the programs distribution 
#JDns.properties=TestFiles/#JDns.properties
##JDns.debug=
#JDns.ra=
JDns.dnsPort=8888
JDns.adminPort=8889
#JDns.bindAddress=192.168.1.120
#JDns.timeout=1000
#JDns.udp.bindAddress=192.168.1.120
# put UPD on the same port as TCP
##JDns.udpPort=
#JDns.udpTimeout=1000
#JDns.tcpPort=	
#JDns.tcpBindAddress=
#JDns.tcpBacklog=
#JDns.tcpTimeout=
JDns.dnsDir=src/test/java/resources/TestFiles
# Relative to JDns.dnsDir (TestDns replaces it with a temporary copy)
JDns.dynamicFileName=dynamic.txt
JDns.zone.dir=src/test/java/resources/TestFiles/zones
ILogger=us.bringardner.parley.core.BjlLogger
LogLevel=DEBUG